In [1]:
import pandas as pd
import numpy as np
import missingno as mgno
import plotly.express as px
from dash import Dash,html,dcc,dash_table,Output,Input,callback

In [2]:
df = pd.read_csv('KaggleV2-May-2016.csv')
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [3]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [4]:
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'],format = "%Y-%m-%dT%H:%M:%SZ")
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'],format = "%Y-%m-%dT%H:%M:%SZ")
df['Scholarship'] = df['Scholarship'].replace({0:'No',1:'yes'})
df['Hipertension'] = df['Hipertension'].replace({0:'No',1:'yes'})
df['Diabetes'] = df['Diabetes'].replace({0:'No',1:'yes'})
df['Alcoholism'] = df['Alcoholism'].replace({0:'No',1:'yes'})
df['Handcap'] = df['Handcap'].replace({0:'No',1:'yes'})
df['SMS_received'] = df['SMS_received'].replace({0:'No',1:'yes'})
df['No-show'] = df['No-show'].replace({'Yes':'No','No':'Yes'})
df = df.rename(columns={'No-show':'Show up'})
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Show up
0,2.987250e+13,5642903,F,2016-04-29 18:38:08,2016-04-29,62,JARDIM DA PENHA,No,yes,No,No,No,No,Yes
1,5.589978e+14,5642503,M,2016-04-29 16:08:27,2016-04-29,56,JARDIM DA PENHA,No,No,No,No,No,No,Yes
2,4.262962e+12,5642549,F,2016-04-29 16:19:04,2016-04-29,62,MATA DA PRAIA,No,No,No,No,No,No,Yes
3,8.679512e+11,5642828,F,2016-04-29 17:29:31,2016-04-29,8,PONTAL DE CAMBURI,No,No,No,No,No,No,Yes
4,8.841186e+12,5642494,F,2016-04-29 16:07:23,2016-04-29,56,JARDIM DA PENHA,No,yes,yes,No,No,No,Yes

In [5]:
df['Waiting_hours'] = (df['AppointmentDay'] - df['ScheduledDay']).dt.total_seconds() / 3600
df = df[df['Waiting_hours'] >= 0]
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,Show up,Waiting_hours
5,9.598513e+13,5626772,F,2016-04-27 08:36:51,2016-04-29,76,REPÚBLICA,No,yes,No,No,No,No,Yes,39.385833
6,7.336882e+14,5630279,F,2016-04-27 15:05:12,2016-04-29,23,GOIABEIRAS,No,No,No,No,No,No,No,32.913333
7,3.449833e+12,5630575,F,2016-04-27 15:39:58,2016-04-29,39,GOIABEIRAS,No,No,No,No,No,No,No,32.333889
9,7.812456e+13,5629123,F,2016-04-27 12:48:25,2016-04-29,19,CONQUISTA,No,No,No,No,No,No,Yes,35.193056
10,7.345362e+14,5630213,F,2016-04-27 14:58:11,2016-04-29,30,NOVA PALESTINA,No,No,No,No,No,No,Yes,33.030278

In [6]:
df['Neighbourhood'].unique()
neighborhoods = [
    'All','JARDIM DA PENHA', 'MATA DA PRAIA', 'PONTAL DE CAMBURI',
    'REPÚBLICA', 'GOIABEIRAS', 'ANDORINHAS', 'CONQUISTA',
    'NOVA PALESTINA', 'DA PENHA', 'TABUAZEIRO', 'BENTO FERREIRA',
    'SÃO PEDRO', 'SANTA MARTHA', 'SÃO CRISTÓVÃO', 'MARUÍPE',
    'GRANDE VITÓRIA', 'SÃO BENEDITO', 'ILHA DAS CAIEIRAS',
    'SANTO ANDRÉ', 'SOLON BORGES', 'BONFIM', 'JARDIM CAMBURI',
    'MARIA ORTIZ', 'JABOUR', 'ANTÔNIO HONÓRIO', 'RESISTÊNCIA',
    'ILHA DE SANTA MARIA', 'JUCUTUQUARA', 'MONTE BELO',
    'MÁRIO CYPRESTE', 'SANTO ANTÔNIO', 'BELA VISTA', 'PRAIA DO SUÁ',
    'SANTA HELENA', 'ITARARÉ', 'INHANGUETÁ', 'UNIVERSITÁRIO',
    'SÃO JOSÉ', 'REDENÇÃO', 'SANTA CLARA', 'CENTRO', 'PARQUE MOSCOSO',
    'DO MOSCOSO', 'SANTOS DUMONT', 'CARATOÍRA', 'ARIOVALDO FAVALESSA',
    'ILHA DO FRADE', 'GURIGICA', 'JOANA D´ARC', 'CONSOLAÇÃO',
    'PRAIA DO CANTO', 'BOA VISTA', 'MORADA DE CAMBURI', 'SANTA LUÍZA',
    'SANTA LÚCIA', 'BARRO VERMELHO', 'ESTRELINHA', 'FORTE SÃO JOÃO',
    'FONTE GRANDE', 'ENSEADA DO SUÁ', 'SANTOS REIS', 'PIEDADE',
    'JESUS DE NAZARETH', 'SANTA TEREZA', 'CRUZAMENTO',
    'ILHA DO PRÍNCIPE', 'ROMÃO', 'COMDUSA', 'SANTA CECÍLIA',
    'VILA RUBIM', 'DE LOURDES', 'DO QUADRO', 'DO CABRAL', 'HORTO',
    'SEGURANÇA DO LAR', 'ILHA DO BOI', 'FRADINHOS', 'NAZARETH',
    'AEROPORTO', 'ILHAS OCEÂNICAS DE TRINDADE', 'PARQUE INDUSTRIAL'
]
age_group = [
    'All','Child','Young Adult','Adult','Senior','Elderly'
]

In [7]:
app = Dash()
app.layout = html.Div(style={'backgroundColor': '#f8f9fa', 'padding': '20px'}, children=[
    html.Div([
        html.H1('Medical Appointments Analysis', style={'textAlign': 'center', 'color': '#2c3e50'}),
        html.Div([
            html.Div([
                html.Label("Select Neighborhood:", style={'fontWeight': 'bold'}),
                dcc.Dropdown(
                    id='dropdown-1',
                    options=[{"label": name, "value": name} for name in neighborhoods],
                    value='All',
                    style={'width': '100%'}
                )
            ], style={'width': '48%', 'display': 'inline-block', 'paddingRight': '2%'}),
            html.Div([
                html.Label("Select Age Group:", style={'fontWeight': 'bold'}),
                dcc.Dropdown(
                    id='dropdown-2',
                    options=[{"label": age, "value": age} for age in age_group],
                    value='All',
                    style={'width': '100%'}
                )
            ], style={'width': '48%', 'display': 'inline-block'}),
        ], style={'marginBottom': '20px'}),
    ], style={'backgroundColor': '#ffffff', 'padding': '20px', 'borderRadius': '10px', 'boxShadow': '0 2px 6px rgba(0,0,0,0.1)'}),

    html.Div(id='kpis_container', style={'display': 'flex', 'gap': '20px', 'justifyContent': 'center', 'marginTop': '20px'}),

    html.Div([
        dcc.Graph(id='figure_1', style={'width': '50%', 'display': 'inline-block'}),
        dcc.Graph(id='figure_2', style={'width': '50%', 'display': 'inline-block'})
    ], style={'marginTop': '20px'}),

    html.Div([
        dcc.Graph(id='figure_3', style={'width': '50%', 'display': 'inline-block'}),
        dcc.Graph(id='figure_4', style={'width': '50%', 'display': 'inline-block'})
    ]),

    html.Div([
        dcc.Graph(id='figure_5', style={'width': '100%', 'display': 'inline-block'})
    ]),

    html.Div(id='table-container', style={'marginTop': '30px'})
])

@app.callback(
    Output('kpis_container','children'),
    Input('dropdown-1','value'),
    Input('dropdown-2','value')
)

def update_kpis(input1,input2):
    if input1 == 'All':
        filtered_df = df
    else:
        filtered_df = df[df['Neighbourhood']== input1]
    if input2 == 'All':
        filtered_df2 = filtered_df
    else:
        if input2 == 'Child':
            filtered_df2 = filtered_df[filtered_df['Age'] <= 17]
        elif input2 == 'Young Adult':
            filtered_df2 = filtered_df[(filtered_df['Age'] > 17)&(filtered_df['Age'] <= 34)]
        elif input2 == 'Adult':
            filtered_df2 = filtered_df[(filtered_df['Age'] > 34)&(filtered_df['Age'] <= 54)]
        elif input2 == 'Senior':
            filtered_df2 = filtered_df[(filtered_df['Age'] > 54)&(filtered_df['Age'] <= 74)]
        else:
            filtered_df2 = filtered_df[filtered_df['Age'] >= 75]

    total_patients = filtered_df2.shape[0]
    show_up_count = (filtered_df2['Show up'] == 'Yes').sum()
    no_show_count = (filtered_df2['Show up'] == 'No').sum()
    attendence_rate = (show_up_count / (show_up_count + no_show_count)) * 100
    filtered_df5 = filtered_df2[filtered_df2['Show up'] == 'Yes']
    waiting_time = filtered_df5['Waiting_hours'].mean()
    scholarship_count = (filtered_df2['Scholarship'] == 'yes').sum()
    no_scholarship_count = (filtered_df2['Scholarship'] == 'No').sum()
    Scholarship_rate = (scholarship_count / (scholarship_count + no_scholarship_count)) * 100
    received_count = (filtered_df2['SMS_received'] == 'yes').sum()
    no_received_count = (filtered_df2['SMS_received'] == 'No').sum()
    received_message = (received_count / (received_count + no_received_count)) * 100
    return [
            html.Div([
                html.H4("Total Patients"),
                html.P(f"{total_patients}", style={'fontSize': '24px', 'fontWeight': 'bold'})
            ], style=kpi_style()),
    
            html.Div([
                html.H4("Attendence Rate"),
                html.P(f"{attendence_rate:.2f}%", style={'fontSize': '24px', 'fontWeight': 'bold'})
            ], style=kpi_style()),
    
            html.Div([
                html.H4("Avg Waiting Time"),
                html.P(f"{waiting_time:.2f}/hr", style={'fontSize': '24px', 'fontWeight': 'bold'})
            ], style=kpi_style()),
    
            html.Div([
                html.H4("Scholarship_rate"),
                html.P(f"{Scholarship_rate:.2f}%", style={'fontSize': '24px', 'fontWeight': 'bold'})
            ], style=kpi_style()),
            html.Div([
                html.H4("received_message"),
                html.P(f"{received_message:.2f}%", style={'fontSize': '24px', 'fontWeight': 'bold'})
            ], style=kpi_style())
        ]

def kpi_style():
    return {
        'padding': '10px',
        'border': '1px solid #ccc',
        'borderRadius': '10px',
        'width': '200px',
        'textAlign': 'center',
        'boxShadow': '2px 2px 8px rgba(0,0,0,0.1)'
    }

@app.callback(
    Output('figure_1','figure'),
    Output('figure_2','figure'),
    Output('figure_3','figure'),
    Output('figure_4','figure'),
    Output('figure_5','figure'),
    Input('dropdown-1','value'),
    Input('dropdown-2','value')
)
def update_graphs(input1,input2):
    if input1 == 'All':
        filtered_df3 = df
    else:
        filtered_df3 = df[df['Neighbourhood']== input1]
    if input2 == 'All':
        filtered_df4 = filtered_df3
    else:
        if input2 == 'Child':
            filtered_df4 = filtered_df3[filtered_df3['Age'] <= 17]
        elif input2 == 'Young Adult':
            filtered_df4 = filtered_df3[(filtered_df3['Age'] > 17)&(filtered_df3['Age'] <= 34)]
        elif input2 == 'Adult':
            filtered_df4 = filtered_df3[(filtered_df3['Age'] > 34)&(filtered_df3['Age'] <= 54)]
        elif input2 == 'Senior':
            filtered_df4 = filtered_df3[(filtered_df3['Age'] > 54)&(filtered_df3['Age'] <= 74)]
        else:
            filtered_df4 = filtered_df3[filtered_df3['Age'] >= 75]

    fig1=px.pie(filtered_df4,'Gender',title = 'Ratio of Genders')
    fig2=px.histogram(filtered_df4,x='Age',title = "distribution of age")
    conditions = ['Hipertension', 'Diabetes', 'Alcoholism', 'Handcap']

    df_melted = filtered_df4[conditions].melt(var_name='Condition', value_name='Status')
    
    fig3 = px.histogram(
        df_melted,
        x='Condition',
        color='Status',
        barmode='group',
        title='Distribution of Yes/No for Medical Conditions',
        labels={'Condition': 'Medical Condition', 'value': 'Count'}
    )

    filtered_df4_0 = filtered_df4.copy()
    filtered_df4_0['Weekday'] = filtered_df4_0['AppointmentDay'].dt.day_name()
    weekday_attendance = filtered_df4_0[filtered_df4_0['Show up'] == 'Yes']['Weekday'].value_counts().sort_index()
    fig4= px.bar(
        x=weekday_attendance.index,
        y=weekday_attendance.values,
        labels={'x': 'Weekday', 'y': 'Number of Show-Ups'},
        title='Attendance per Weekday',
    )

    filtered_df4_1 = filtered_df4.copy()
    
    factors = ['Scholarship', 'Hipertension', 'Diabetes', 'Alcoholism', 'SMS_received']
    reason_counts = {}
    total_no_shows = (filtered_df4_1['Show up'] == 'No').sum()
    
    for col in factors:
        count = filtered_df4_1[(filtered_df4_1[col] == 'yes') & (filtered_df4_1['Show up'] == 'No')].shape[0]
        if (col == 'SMS_received') or (col == 'Scholarship'):
            percent = (1 - (count / total_no_shows)) * 100
            col = 'NO ' + col
        else:
             percent = (count / total_no_shows) * 100
        reason_counts[col] = percent
    
    reason_df = pd.DataFrame.from_dict(reason_counts, orient='index', columns=['Percentage']).reset_index()
    reason_df.columns = ['Reason', 'Percentage']
    
    fig5 = px.bar(reason_df, x='Reason', y='Percentage',
                  title='Contribution to No-Shows by Reason (Yes Group)',
                  labels={'Percentage': '% of All No-Shows'},
                  color='Percentage', color_continuous_scale='reds')



    return fig1,fig2,fig3,fig4,fig5
@app.callback(
    Output('table-container', 'children'),
    Input('dropdown-1','value'),
    Input('dropdown-2','value')
)
def update_table(input1,input2):
    if input1 == 'All':
        filtered_df5 = df
    else:
        filtered_df5 = df[df['Neighbourhood']== input1]
    if input2 == 'All':
        filtered_df6 = filtered_df5
    else:
        if input2 == 'Child':
            filtered_df6 = filtered_df5[filtered_df5['Age'] <= 17]
        elif input2 == 'Young Adult':
            filtered_df6 = filtered_df5[(filtered_df5['Age'] > 17)&(filtered_df5['Age'] <= 34)]
        elif input2 == 'Adult':
            filtered_df6 = filtered_df5[(filtered_df5['Age'] > 34)&(filtered_df5['Age'] <= 54)]
        elif input2 == 'Senior':
            filtered_df6 = filtered_df5[(filtered_df5['Age'] > 54)&(filtered_df5['Age'] <= 74)]
        else:
            filtered_df6 = filtered_df5[filtered_df5['Age'] >= 75]

    return dash_table.DataTable(
        data=filtered_df6.to_dict('records'),
        columns=[{'name': i, 'id': i} for i in filtered_df6.columns],
        page_size=5,
        style_table={'overflowX': 'auto'},
        style_cell={'textAlign': 'left'}
    )
if __name__ == '__main__':
    app.run()